
        
<div> 
			<h2 style =" margin-top: 5px;" >&emsp;&emsp;&emsp;&emsp;Name: Frances Aneth Rosales <br> &emsp;&emsp;&emsp;&emsp;Student Number: 2021044631 <br> &emsp;&emsp;&emsp;&emsp;FA6  </h2>
</div>
		<br><br><br>

Click to direct line. 
 
<b>
<li><a href="#sectionintro">  Introduction </a></li>
<li><a href="#sectioncloak">  a. Cloak Summary Data </a></li> 
<li><a href="#sectionMiss">  b. Mischief Summary Data </a></li>
<li><a href="#sectionwelch">  c. Welch Two Sample t-test </a></li>
<li><a href="#sectionmeandiff">  d. Mean Differences ES </a></li>
</b>

<br> <br>


# I. Introduction
<b> Independent samples t-test for Invisibility Cloak data set</b>

Showing the Data

<section id="sectionintro"> </section>

In [37]:
import pandas as pd

file_path = "Invisibility_Cloak.xlsx"
xls = pd.ExcelFile(file_path)

data_sheet = pd.read_excel(file_path, sheet_name="Invisibility Cloak")

datframe_c = pd.DataFrame(data_sheet)
print(datframe_c)

    Participant  Cloak  Mischief
0             1      0         3
1             2      0         1
2             3      0         5
3             4      0         4
4             5      0         6
5             6      0         4
6             7      0         6
7             8      0         2
8             9      0         0
9            10      0         5
10           11      0         4
11           12      0         5
12           13      1         4
13           14      1         3
14           15      1         6
15           16      1         6
16           17      1         8
17           18      1         5
18           19      1         5
19           20      1         4
20           21      1         2
21           22      1         5
22           23      1         7
23           24      1         5

# a. Cloak Summary Data

<section id="sectioncloak"> </section>

In [39]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis, iqr, scoreatpercentile

file_path = "Invisibility_Cloak.xlsx"
data_sheet = pd.read_excel(file_path, sheet_name="Invisibility Cloak")

list_num = data_sheet["Cloak"]

mean_value = np.mean(list_num)
median_value = np.median(list_num)
mode_value = list_num.mode().iloc[0] 
std = np.std(list_num)
variance = np.var(list_num)
skewness_value = skew(list_num)
kurtosis_value = kurtosis(list_num)

q1 = np.percentile(list_num, 25)
q2 = np.percentile(list_num, 50)
q3 = np.percentile(list_num, 75)

iqr_value = iqr(list_num)

d9 = scoreatpercentile(list_num, 90)
p95 = scoreatpercentile(list_num, 95)

std_error_skewness = np.sqrt(6 * len(list_num) * (len(list_num) - 1) / ((len(list_num) - 2) * (len(list_num) + 1) * (len(list_num) + 3)))

results_df_cloak = pd.DataFrame({
    "Cloak Summary Data": ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    "Data": ["Valid", "Mode", "Mean", "Median", "Standard Deviation", "Variance", "Skewness", "Standard Error of Skewness", "Kurtosis", "Q1", "Q2", "Q3", "D9", "P95"],
    "Score": [len(list_num), mode_value, mean_value, median_value, std, variance, skewness_value, std_error_skewness, kurtosis_value, q1, q2, q3, d9, p95]
})

results_df_cloak["Score"] = results_df_cloak["Score"].apply(lambda x: "{:.3f}".format(x))
results_df_cloak

   Cloak Summary Data                        Data   Score
0                                           Valid  24.000
1                                            Mode   0.000
2                                            Mean   0.500
3                                          Median   0.500
4                              Standard Deviation   0.500
5                                        Variance   0.250
6                                        Skewness   0.000
7                      Standard Error of Skewness   0.472
8                                        Kurtosis  -2.000
9                                              Q1   0.000
10                                             Q2   0.500
11                                             Q3   1.000
12                                             D9   1.000
13                                            P95   1.000

# b. Mischief Summary Data

<section id="sectionMiss"> </section>

In [43]:

list_num2 = data_sheet["Mischief"]
mean_value2 = np.mean(list_num2)
median_value2 = np.median(list_num2)
mode_value2 = list_num2.mode().iloc[0]  
std2 = np.std(list_num2)
variance2 = np.var(list_num2)
skewness_value2 = skew(list_num2)
kurtosis_value2 = kurtosis(list_num2)
q1_2 = np.percentile(list_num2, 25)
q2_2 = np.percentile(list_num2, 50)
q3_2 = np.percentile(list_num2, 75)
iqr_value2 = iqr(list_num2)

d9_2 = scoreatpercentile(list_num2, 90)
p95_2 = scoreatpercentile(list_num2, 95)

std_error_skewness2 = np.sqrt(6 * len(list_num2) * (len(list_num2) - 1) / ((len(list_num2) - 2) * (len(list_num2) + 1) * (len(list_num2) + 3)))

results_df_mischief = pd.DataFrame({
    "Mischief Summary Data": ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    "Data": ["Valid", "Mode", "Mean", "Median", "Standard Deviation", "Variance", "Skewness", "Standard Error of Skewness", "Kurtosis", "Q1", "Q2", "Q3", "D9", "P95"],
    "Score": [len(list_num2), mode_value2, mean_value2, median_value2, std2, variance2, skewness_value2, std_error_skewness2, kurtosis_value2, q1_2, q2_2, q3_2, d9_2, p95_2]
})

results_df_mischief["Score"] = results_df_mischief["Score"].apply(lambda x: "{:.3f}".format(x))
results_df_mischief

   Mischief Summary Data                        Data   Score
0                                              Valid  24.000
1                                               Mode   5.000
2                                               Mean   4.375
3                                             Median   5.000
4                                 Standard Deviation   1.821
5                                           Variance   3.318
6                                           Skewness  -0.482
7                         Standard Error of Skewness   0.472
8                                           Kurtosis   0.089
9                                                 Q1   3.750
10                                                Q2   5.000
11                                                Q3   5.250
12                                                D9   6.000
13                                               P95   6.850

# c. Welch Two Sample t-test

<section id="sectionwelch"> </section>

In [70]:

t_statistic, p_value = ttest_ind(list_num, list_num2, equal_var=False)

ci_low, ci_high = t_statistic - 1.96 * ((list_num.var()/len(list_num)) + (list_num2.var()/len(list_num2)))**0.5, \
                  t_statistic + 1.96 * ((list_num.var()/len(list_num)) + (list_num2.var()/len(list_num2)))**0.5

print("Welch Two Sample t-test:")
print(f"t = {t_statistic:.3f}, df = {min(len(list_num)-1, len(list_num2)-1):.1f}, p-value = {p_value:.2e}")
print("Alternative hypothesis: true difference in means is not equal to 0")
print(f"95 percent confidence interval: ({ci_low:.6f}, {ci_high:.6f})")
print("Sample estimates:")
print(f"Mean in Cloak: {list_num.mean()}")
print(f"Mean in Mischief: {list_num2.mean()}")

Welch Two Sample t-test:
t = -9.839, df = 23.0, p-value = 2.49e-10
Alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval: (-10.610719, -9.066827)
Sample estimates:
Mean in Cloak: 0.5
Mean in Mischief: 4.375

# d. Mean Differences ES

<section id="sectionmeandiff"> </section>

In [69]:

mean_diff = pg.compute_effsize(list_num, list_num2, paired=False, eftype='Cohen')

mean_difference = list_num.mean() - list_num2.mean()

ci_low, ci_high = pg.compute_bootci(list_num - list_num2, func=np.mean, confidence=0.95)

t_statistic, p_value = ttest_rel(list_num, list_num2)

print(f"Mean Difference ES: {mean_difference:.2f} [{ci_low:.2f}, {ci_high:.2f}]")
print(f"Variance of mean difference: {variance_mean_difference:.2f}")
print(f"P-value of mean difference: {p_value:.4f}")

Mean Difference ES: -3.88 [-4.58, -3.25]
Variance of mean difference: 2.94
P-value of mean difference: 0.0000